#!/bin/sh

# some tests have build path compiled-in, we need to rebuild
# everything to make sure the path is the temporary one used for
# the autopkgtest. NB: cmake hates relocation, so we'd have to
# mangle CMakeCache.txt to get away with a as-needed-rebuild :/
debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules build 2>&1

[ -e debian/tests.home ] || mkdir debian/tests.home
export HOME="$(pwd)/debian/tests.home"
xvfb-run -a --server-args="-screen 0 1024x768x24+32" \
    dbus-launch --exit-with-session debian/tests/testsuite.xsession
ret=$?
rm -rf debian/tests.home
exit $ret
